package com.android.networkstack.inprocess;

/* This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int config_captive_portal_fallback_probe_specs = 2130771968;
        public static final int config_captive_portal_fallback_urls = 2130771969;
        public static final int config_default_dns_servers = 2130771970;
        public static final int default_captive_portal_fallback_probe_specs = 2130771971;
        public static final int default_captive_portal_fallback_urls = 2130771972;
    }

    public static final class integer {
        public static final int config_captive_portal_dns_probe_timeout = 2130837504;
        public static final int default_captive_portal_dns_probe_timeout = 2130837505;
    }

    public static final class string {
        public static final int config_captive_portal_http_url = 2130903040;
        public static final int config_captive_portal_https_url = 2130903041;
        public static final int default_captive_portal_http_url = 2130903042;
        public static final int default_captive_portal_https_url = 2130903043;
    }
}
